export type LegalDoc = {
  id: "privacy" | "terms" | "safety" | "about";
  title: string;
  effective?: string;
  sections: { heading?: string; body: string }[];
};

export const legalDocs: Record<LegalDoc["id"], LegalDoc> = {
  privacy: {
    id: "privacy",
    title: "SMART WATT Privacy Policy",
    effective: "July 2026",
    sections: [
      { heading: "1. Introduction", body: "SMART WATT is an internet-connected device-control platform powered by NoskyTech. This Privacy Policy explains how information is collected, used, processed and protected when users access the SMART WATT web application and connected hardware.\n\nBy using SMART WATT, users acknowledge the practices described in this Privacy Policy." },
      { heading: "2. Information We Collect", body: "We may process information required to operate and protect the service, including account email address, authentication information managed through Supabase, device identification information, device connection status, commanded relay state, confirmed relay state, command and update timestamps, basic technical and diagnostic information, and browser and network information required to provide the service.\n\nSMART WATT does not require users to provide unnecessary personal information to control a compatible device." },
      { heading: "3. Account Information", body: "Authentication information is processed through Supabase Authentication. Passwords are not displayed inside SMART WATT and should not be shared with other people. Users are responsible for protecting their login credentials and reporting suspected unauthorised account access." },
      { heading: "4. Device and Usage Information", body: "SMART WATT may process device information such as device code, device name, online or offline status, requested control state, confirmed physical state, connection timestamps and device response information. This information is used to provide remote control, display device status, confirm command execution and diagnose service issues." },
      { heading: "5. How We Use Information", body: "Information may be used to authenticate users, provide remote device control, deliver commands to connected hardware, display confirmed device state, maintain account and device security, diagnose errors and connectivity problems, improve reliability and user experience, prevent unauthorised access or misuse, and comply with applicable legal obligations." },
      { heading: "6. Cloud Infrastructure", body: "SMART WATT uses cloud infrastructure, including Supabase, to support authentication, database access and realtime device communication. Information may be processed by these providers according to their own service terms and privacy practices. NoskyTech does not sell personal information." },
      { heading: "7. Device Control and Command Processing", body: "When a user sends an ON or OFF command, SMART WATT records the requested state in the cloud. The connected controller reads the command, operates the physical relay and reports the confirmed state back to the platform. Commands, connection status and timestamps may be stored for service operation, diagnostics and security." },
      { heading: "8. Data Security", body: "NoskyTech uses reasonable technical and organisational measures intended to protect information against unauthorised access, misuse, alteration or loss. These measures may include authentication, encrypted network communication, access controls and database security policies.\n\nHowever, no internet-based system, cloud service or connected device can guarantee complete security. Users should use strong passwords, protect their accounts and secure their home or workplace network." },
      { heading: "9. Data Retention", body: "Information may be retained for as long as necessary to provide the service, maintain device functionality, protect accounts, resolve technical issues, and satisfy legitimate business or legal requirements. Data that is no longer required may be deleted or anonymised when reasonably practical." },
      { heading: "10. User Rights", body: "Depending on applicable law, users may request access to, correction of or deletion of certain personal information. Requests may be submitted through the contact details provided in this policy. Some information may need to be retained where required for security, fraud prevention, dispute resolution or legal compliance." },
      { heading: "11. Children's Privacy", body: "SMART WATT is not intended for independent use by children who are not legally permitted to enter into digital-service agreements. Parents or guardians should supervise a child's use of connected electrical equipment." },
      { heading: "12. Third-Party Services", body: "SMART WATT may depend on third-party infrastructure, internet providers, hosting platforms and authentication services. NoskyTech is not responsible for the privacy practices or service availability of independent third parties." },
      { heading: "13. Voice Control and Cypher", body: "SMART WATT may use browser-based speech recognition to interpret voice commands initiated by the user. Microphone access is requested only when the user activates Cypher.\n\nIn the initial version, voice recognition and spoken feedback may be handled through browser-supported speech services. Depending on the browser and device, speech processing may involve services provided by the browser or operating-system provider.\n\nSMART WATT does not intentionally keep the microphone active continuously. Raw audio recordings are not stored by NoskyTech unless a future voice service is introduced with appropriate notice and user controls.\n\nRecognised command text may be processed temporarily to determine whether the user requested a supported action, such as turning the connected bulb on or off. Users should avoid speaking confidential or sensitive information while using voice control.\n\nInformation that may be processed for voice control includes recognised voice-command text, voice-control errors, command timestamps and microphone permission status where technically available." },
      { heading: "14. Changes to This Policy", body: "This Privacy Policy may be updated as the service, technology or legal requirements change. The updated version will display a revised effective date. Continued use of SMART WATT after an update means the user acknowledges the revised policy." },
      { heading: "15. Contact Information", body: "Questions or requests concerning this Privacy Policy may be sent to NoskyTech.\n\nEmail: noskytech1@gmail.com\nWebsite: https://noskytech.vercel.app" },
    ],
  },
  terms: {
    id: "terms",
    title: "SMART WATT Terms of Use",
    effective: "July 2026",
    sections: [
      { heading: "1. Acceptance of Terms", body: "These Terms of Use govern access to and use of SMART WATT, an internet-connected device-control platform powered by NoskyTech. By creating an account, accessing the application or operating connected hardware through SMART WATT, the user agrees to these Terms. Users who do not agree should not use the service." },
      { heading: "2. Description of the Service", body: "SMART WATT allows authorised users to send commands through a web application to compatible internet-connected electrical control hardware. The current version supports remote ON and OFF control of one connected bulb through an ESP32 controller, cloud database and relay module. Available features may change as the service develops." },
      { heading: "3. Account Responsibilities", body: "Users are responsible for providing accurate account information, keeping login credentials confidential, preventing unauthorised use of their account, signing out from shared devices, and informing NoskyTech of suspected account compromise. Actions completed through an authenticated account may be treated as authorised actions unless reported otherwise." },
      { heading: "4. Acceptable Use", body: "Users must not attempt to access another user's account or device, interfere with the service or cloud infrastructure, bypass security controls, upload malicious code, reverse engineer protected components where prohibited by law, use the service for unlawful or dangerous purposes, or connect unsupported or unsafe electrical equipment." },
      { heading: "5. Electrical Safety", body: "SMART WATT controls electrical hardware through an internet-connected device. Installation, wiring, inspection and maintenance involving mains electricity must be performed by a qualified person. Users must not handle exposed live wiring, operate damaged equipment or bypass protective components. Before servicing connected hardware, electrical power must be safely isolated.\n\nNoskyTech is not responsible for injury, fire, equipment damage or property loss resulting from improper wiring, unsafe installation, unauthorised modification or misuse." },
      { heading: "6. Internet and Power Dependence", body: "SMART WATT depends on electrical power, internet connectivity, Wi-Fi availability, cloud infrastructure, ESP32 operation, relay condition and user-device compatibility. Power outages, weak Wi-Fi, internet interruptions, cloud-service interruptions or hardware faults may temporarily prevent remote operation." },
      { heading: "7. Command Delays and Failures", body: "Remote commands may be delayed, rejected or not executed due to device disconnection, network congestion, cloud interruption, authentication failure, hardware failure, power loss, software errors or device maintenance.\n\nUsers must verify the confirmed physical state shown by the system and should not rely only on the commanded state. SMART WATT must not be used as the sole safety control for critical equipment." },
      { heading: "8. User Responsibility", body: "Users are responsible for determining whether SMART WATT is suitable for their intended equipment and environment. Users must maintain safe manual controls and protective devices where appropriate. The platform should not be used for medical, emergency, life-support or other safety-critical systems unless specifically certified for that purpose." },
      { heading: "9. Voice Commands", body: "Cypher voice control is provided for convenience. Speech recognition may misunderstand commands due to background noise, pronunciation, microphone quality, browser limitations or network conditions.\n\nUsers must verify the commanded state and confirmed physical state shown in SMART WATT. Users should not rely exclusively on voice control for safety-critical operations. Where a command is unclear, unsupported or not confirmed by the connected device, the user should use the manual control and verify the equipment directly.\n\nCypher must not be used as the sole emergency shutoff or electrical isolation mechanism." },
      { heading: "10. Intellectual Property", body: "SMART WATT, NoskyTech branding, interface designs, software, documentation, product names and related materials are owned by or licensed to NoskyTech. Users receive a limited, revocable and non-transferable right to use the service for its intended purpose. No ownership rights are transferred to users." },
      { heading: "11. Service Changes", body: "NoskyTech may improve, modify, suspend or discontinue features when reasonably necessary for security, maintenance, legal compliance, technical improvement, product development or infrastructure changes. Reasonable efforts may be made to communicate major changes where practical." },
      { heading: "12. Disclaimer of Warranties", body: "SMART WATT is provided on an \"as available\" basis. To the maximum extent permitted by law, NoskyTech does not guarantee uninterrupted service, error-free operation, immediate command delivery, compatibility with every network or appliance, or continuous third-party service availability. Nothing in these Terms excludes rights that cannot legally be excluded." },
      { heading: "13. Limitation of Liability", body: "To the maximum extent permitted by applicable law, NoskyTech will not be liable for indirect, incidental, special or consequential loss arising from internet failure, power interruption, delayed commands, improper installation, device misuse, unauthorised access, unsupported hardware or third-party service interruption. Users remain responsible for safe installation and operation of connected electrical equipment." },
      { heading: "14. Suspension or Termination", body: "Access may be suspended or terminated where a user violates these Terms, creates a security risk, uses the service unlawfully, attempts unauthorised access, interferes with infrastructure, or endangers people or property. Users may stop using the service and sign out at any time." },
      { heading: "15. Changes to These Terms", body: "These Terms may be updated as SMART WATT evolves. The revised version will display an updated effective date. Continued use after changes means the user accepts the revised Terms." },
      { heading: "16. Contact Information", body: "Questions about these Terms may be sent to NoskyTech.\n\nEmail: noskytech1@gmail.com\nWebsite: https://noskytech.vercel.app" },
    ],
  },
  safety: {
    id: "safety",
    title: "Electrical Safety Notice",
    effective: "July 2026",
    sections: [
      { body: "SMART WATT operates electrical equipment through an internet-connected controller and relay. Installation or maintenance involving 220–240 V mains electricity must be performed by a qualified electrician or competent technician." },
      { heading: "Always disconnect power first", body: "Always disconnect electrical power before opening, wiring, inspecting or servicing the device. Physically isolate mains power before performing any electrical work." },
      { heading: "Do not use SMART WATT with", body: "• Exposed wiring\n• Damaged relay modules\n• Loose electrical terminals\n• Overloaded circuits\n• Wet equipment\n• Unsupported high-power appliances\n• Missing protective devices" },
      { heading: "Use correctly rated components", body: "• Circuit breakers\n• Fuses\n• Enclosures\n• Wiring\n• Terminals\n• Isolation components" },
      { heading: "Important limitations", body: "Remote switching must not replace essential manual isolation or emergency controls. Never assume an appliance is electrically safe only because the application displays OFF.\n\nInternet, cloud, software or hardware failures may prevent a remote command from executing. The user and installer are responsible for verifying the safety and suitability of the installation." },
    ],
  },
  about: {
    id: "about",
    title: "About SMART WATT",
    sections: [
      { body: "SMART WATT is a connected device-control platform powered by NoskyTech. It enables authorised users to remotely control compatible electrical equipment through a secure web interface, cloud connection and internet-connected controller." },
      { heading: "The current prototype includes", body: "• One connected bulb\n• One ESP32 controller\n• One relay output\n• Supabase cloud infrastructure\n• Remote ON and OFF control\n• Realtime status updates\n• Confirmed physical relay state" },
      { body: "SMART WATT is part of NoskyTech's vision for accessible, intelligent and connected automation systems." },
    ],
  },
};
